//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Product_Serial { get; set; }
        public string Product_Name { get; set; }
        public int Product_Count { get; set; }
        public long Product_Price { get; set; }
        public string Product_Color { get; set; }
    }
}
